name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Zip Lambda function
      run: |
        cd lambda  # Va dans le dossier contenant le code de la Lambda
        zip -r ../lambda.zip .  # Crée le fichier lambda.zip à la racine du projet
      working-directory: ./lambda  # Change le chemin si nécessaire


    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
    