name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: | 
          ls
          terraform init
      working-directory: ./terraform

    - name: Zip Lambda function
      run: |
        ls
        cd lambda  # Va dans le dossier contenant le code de la Lambda
        zip -r ../lambda.zip .  # Crée le fichier lambda.zip à la racine du projet
        
    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform
    